### ISSUE TITLE
Execution 

### ISSUE THREAD

**Issue by imSunnyk** [vic-vic-/crypto-storage#1]
How to execute this project?
Which Py file to run and how?

**Comment by vic-vic-** [comment]
Hi @imSunnyk 

Let me update the project. I'm going to update it to Django v3. I'll try my best to get around it today. I'll update the Readme file as well for better instructions on running this project.

Thanks.

**Comment by imSunnyk** [comment]
Yes, please update a readme file for instructions....it would be very helpful.

And thank you for the reply.🙂

**Comment by vic-vic-** [comment]
Hi @imSunnyk ,

Please see my latest commit 51ccf75. Read the Getting Started and Basic Usage on the Readme file. If you have other questions let me know. 
FYI. :) @phamhp .

I will close this issue next week if no issues. Thanks.
